---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://api.open-meteo.com/v1/forecast?latitude={{ trmnl.plugin_settings.custom_fields_values.latitude }}&longitude={{ trmnl.plugin_settings.custom_fields_values.longitude }}&daily=weather_code,temperature_2m_max,temperature_2m_min,uv_index_max,precipitation_probability_max,precipitation_probability_min,precipitation_probability_mean&current=temperature_2m,relative_humidity_2m,weather_code,precipitation,is_day&timezone=auto&temperature_unit={{ trmnl.plugin_settings.custom_fields_values.temp_unit }}
polling_headers: ''
polling_body: ''
id: 198477
custom_fields:
- keyname: bio
  name: About This Plugin
  field_type: author_bio
  description: Get a clear snapshot of todayâ€™s weather plus a 5-day forecast, including temperatures, uv indexes and rain chances.
- keyname: latitude
  field_type: string
  name: Latitude
  description: The latitude of your location
  placeholder: Latitude
  help_text: Go to <a href="https://www.latlong.net" target="_blank">https://www.latlong.net</a>, search for the desired place or navigate using the map, then copy the latitude.
- keyname: longitude
  field_type: string
  name: Longitude
  description: The longitude of your location
  placeholder: Longitude
  help_text: Go to <a href="https://www.latlong.net" target="_blank">https://www.latlong.net</a>, search for the desired place or navigate using the map, then copy the longitude.
- keyname: temp_unit
  field_type: select
  name: Temperature Unit
  description: Select the desired temperature unit
  default: celsius
  options:
  - Celsius: celsius
  - Fahrenheit: fahrenheit
- keyname: location_name
  field_type: string
  optional: true
  name: Location Name
  placeholder: Location name
  description: 'Give a name to help identify this location (eg: home, office, city name, etc.)'
  help_text: This name will be displayed at the right side of the plugin title bar.
name: Daily Weather Forecast
refresh_interval: 720
